### ISSUE TITLE
java.lang.IllegalStateException: Observer was not registered

### ISSUE THREAD

**Issue by Addibro** [yuyakaido/CardStackView#161]
When calling recreate() in my main activity the following is thrown:

`java.lang.IllegalStateException: Observer com.yuyakaido.android.cardstackview.CardStackView$1@501c685 was not registered.
        at android.database.Observable.unregisterObserver(Observable.java:69)
        at android.support.v7.widget.RecyclerView$Adapter.unregisterAdapterDataObserver(RecyclerView.java:7017)
        at com.yuyakaido.android.cardstackview.CardStackView.onDetachedFromWindow(CardStackView.java:102)
        at android.view.View.dispatchDetachedFromWindow(View.java:18400)
        at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3777)
        at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3769)
        at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3769)
        at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3769)
        at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3769)
        at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3769)
        at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3769)
        at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3769)
        at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3769)
        at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3769)
        at android.view.ViewRootImpl.dispatchDetachedFromWindow(ViewRootImpl.java:3810)
        at android.view.ViewRootImpl.doDie(ViewRootImpl.java:6753)
        at android.view.ViewRootImpl.die(ViewRootImpl.java:6730)
        at android.view.WindowManagerGlobal.removeViewLocked(WindowManagerGlobal.java:458)
        at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:396)
        at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:124)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4498)
        at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:4760)
        at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4693)
        at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:69)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ClientTransactionHandler.executeTransaction(ClientTransactionHandler.java:55)
        at android.app.ActivityThread.handleRelaunchActivityLocally(ActivityThread.java:4743)
        at android.app.ActivityThread.access$3200(ActivityThread.java:199)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1818)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)`

Please help!

**Comment by shivam21** [comment]
same problem..please help

**Comment by yuyakaido** [comment]
@Addibro @shivam21 
Thank you for detail information and steps to reproduce!
This issue has been fixed in ver. 2.1.2.

**Comment by Addibro** [comment]
Alright, I’ll try it out! Thanks

**Comment by woshiieugene** [comment]
Any solutions to this yet? using version 2.2.0 and still experiencing this error. 

My logs is as follows: 

java.lang.IllegalStateException: Observer com.yuyakaido.android.cardstackview.internal.CardStackDataObserver@21e9af7 was not registered.
        at android.database.Observable.unregisterObserver(Observable.java:69)
        at android.support.v7.widget.RecyclerView$Adapter.unregisterAdapterDataObserver(RecyclerView.java:7017)
        at com.yuyakaido.android.cardstackview.CardStackView.onDetachedFromWindow(CardStackView.java:62)
        at android.view.View.dispatchDetachedFromWindow(View.java:17536)
        at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3683)
        at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3675)
        at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3675)
        at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3675)
        at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3675)
        at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3675)
        at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3675)
        at android.view.ViewRootImpl.dispatchDetachedFromWindow(ViewRootImpl.java:3509)
        at android.view.ViewRootImpl.doDie(ViewRootImpl.java:6407)
        at android.view.ViewRootImpl.die(ViewRootImpl.java:6384)
        at android.view.WindowManagerGlobal.removeViewLocked(WindowManagerGlobal.java:458)
        at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:396)
        at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:125)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4671)
        at android.app.ActivityThread.-wrap5(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1749)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6798)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
